/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public final class Frame_Usuarios extends javax.swing.JFrame {
    private ArrayList <Usuario> listaUsuarios = new ArrayList<>();
    private int id_usuarios;
    
    /**
     * Creates new form Frame_Usuarios
     */
    
    public Frame_Usuarios() {
        initComponents();
    }
    
    public Frame_Usuarios(ArrayList <Usuario> lista, int id) {
        listaUsuarios = lista;
        id_usuarios = id;
        initComponents();
        this.cargarInformacion();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        lbId = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfoId = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfoUsuarios = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInfoSaldo = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        btnMas.setBackground(new java.awt.Color(0, 153, 255));
        btnMas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMas.setForeground(new java.awt.Color(255, 255, 255));
        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(0, 153, 255));
        btnMenos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        lbId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbId.setText("ID");

        lbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario.setText("USUARIO");

        lbSaldo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSaldo.setText("SALDO");

        txtInfoId.setEditable(false);
        txtInfoId.setBackground(new java.awt.Color(255, 255, 255));
        txtInfoId.setColumns(15);
        txtInfoId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInfoId.setRows(5);
        jScrollPane1.setViewportView(txtInfoId);

        txtInfoUsuarios.setEditable(false);
        txtInfoUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        txtInfoUsuarios.setColumns(15);
        txtInfoUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInfoUsuarios.setRows(5);
        jScrollPane2.setViewportView(txtInfoUsuarios);

        txtInfoSaldo.setEditable(false);
        txtInfoSaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtInfoSaldo.setColumns(15);
        txtInfoSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInfoSaldo.setRows(5);
        jScrollPane3.setViewportView(txtInfoSaldo);

        btnSalir.setBackground(new java.awt.Color(0, 153, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setText("ELIMINAR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbUsuario)
                        .addGap(325, 325, 325)
                        .addComponent(lbSaldo)
                        .addGap(186, 186, 186))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 647, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btnMenos)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenos)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMas))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lbId))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSaldo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
        
        
        Usuario nuevoUsuario = new Usuario(id_usuarios, generar_usuario(), generar_saldo());
        
        //Usuario nuevoUsuario = new Usuario(id_usuario, generar_usuario(), generar_saldo());
        listaUsuarios.add(nuevoUsuario);
        cargarInformacion();
        id_usuarios++;
        
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
        Integer num;
        num = Integer.valueOf(txtId.getText());
        boolean bandera = false;
        float menor = 500;
        float donar=0;
        
        for(int i=0; i<listaUsuarios.size(); i++){
            if(num == listaUsuarios.get(i).getId()){
                donar = listaUsuarios.get(i).getSaldo()/10;
                for(int j=0; j<listaUsuarios.size(); j++){
                    if(listaUsuarios.get(j).getSaldo() < menor && (listaUsuarios.get(j).getId() != num)){
                        menor = listaUsuarios.get(j).getSaldo();
                    }
                }
                
                for(int j=0; j<listaUsuarios.size(); j++){
                    if(listaUsuarios.get(j).getSaldo() == menor){
                        listaUsuarios.get(j).setSaldo(listaUsuarios.get(j).getSaldo() + donar);
                    }
                }
                
               listaUsuarios.remove(i);
               bandera = true;
            }
        }
        if(!bandera){
            JOptionPane.showMessageDialog(jPanel1, "El id " + txtId.getText() + " no existe");
        }
        
        cargarInformacion();
        
    }//GEN-LAST:event_btnMenosActionPerformed

    @SuppressWarnings("empty-statement")
    public String generar_usuario(){
        String cadena;
        int num;
        char caracteres[] ={ '¡', '#', '$', '&', '/','?','¿', '.', '_'};
        num = (int)(Math.random()* (90-65)+1)+65;
        cadena = Character.toString(num);
        for(int j=0; j<3; j++){
            cadena += Character.toString((int)(Math.random()* (90-65)+1)+65).toLowerCase();
        }
        for (int i=0; i<3; i++){
            cadena += (int)(Math.random()*10);
        }
        cadena +=caracteres[(int)(Math.random()*8)];
        cadena += Character.toString((int)(Math.random()* (90-65)+1)+65);
        return cadena;
    }
    
    public Float generar_saldo(){
        float saldo;
       // saldo = 10.2f;
       saldo = (float)(Math.random()*(500-100)+1)+100;
        return saldo;
    }
    
    public void cargarInformacion(){
        String id="";
        String usuarios="";
        String saldo="";
        for( Usuario user : listaUsuarios){
            id =id + user.getId() + "\n";
            usuarios = usuarios + user.getUser_name() + "\n";
            saldo = saldo + user.getSaldo() + "\n";
            
            
        }
        txtInfoId.setText(id);
        txtInfoUsuarios.setText(usuarios);
        txtInfoSaldo.setText(saldo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtInfoId;
    private javax.swing.JTextArea txtInfoSaldo;
    private javax.swing.JTextArea txtInfoUsuarios;
    // End of variables declaration//GEN-END:variables
}
