/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Gui_Juego extends javax.swing.JFrame {
    private Usuario jugador= new Usuario();
    private ArrayList <String> personajes= new ArrayList <>();
    private ArrayList <String> partidas= new ArrayList <>();
    private int intentos, partida;
    private Icon iconos[] = new Icon[4];
    int n1;
    String personaje;
    String palabraT="";
    String letrasUsadas="";
    int contador=0;
    float saldo=0;
    int ganadas=0;
    //String lineas;
    /**
     * Creates new form Gui_Juego
     */
    public Gui_Juego() {
        //jugador=usu;
        initComponents();
        
        /*txtJugador.setText(jugador.getNombre());
        txtSaldo.setText(String.valueOf(jugador.getSueldo()));*/
        txtJugador.setText("carlitos");
        txtSaldo.setText(String.valueOf(234));
        personajes.add("pikachu");
        personajes.add("squirtle");
        personajes.add("chrizard");
        personajes.add("bulbasaur");
        personajes.add("eevee");
        
        
        seleccionaPalabra();
        
    }

    public Gui_Juego(Usuario usu) {
        jugador=usu;
        initComponents();
        intentos=4;
        txtIntentos.setText(String.valueOf(intentos));
        txtJugador.setText(jugador.getUser_name());
        txtSaldo.setText(String.valueOf(jugador.getSaldo()));
        //txtJugador.setText("carlitos");
        //txtSaldo.setText(String.valueOf(234));
        personajes.add("PIKACHU");
        personajes.add("SQUIRTLE");
        personajes.add("CHARIZARD");
        personajes.add("BULBASAUR");
        personajes.add("VULPIX");
        personajes.add("VENONAT");
        personajes.add("PIDGEY");
        personajes.add("ODDISH");
        personajes.add("EKANS");
        personajes.add("CLEFAIRY");
        
        llenarPalabras();
        seleccionaPalabra();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtJugador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtIntentos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelImg = new javax.swing.JPanel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnLet1 = new javax.swing.JButton();
        btnLet2 = new javax.swing.JButton();
        btnLet3 = new javax.swing.JButton();
        btnLet4 = new javax.swing.JButton();
        btnLet5 = new javax.swing.JButton();
        btnLet6 = new javax.swing.JButton();
        btnLet7 = new javax.swing.JButton();
        btnLet8 = new javax.swing.JButton();
        btnLet9 = new javax.swing.JButton();
        btnLet10 = new javax.swing.JButton();
        btnLet11 = new javax.swing.JButton();
        btnLet12 = new javax.swing.JButton();
        btnLet13 = new javax.swing.JButton();
        btnLet14 = new javax.swing.JButton();
        btnLet15 = new javax.swing.JButton();
        btnLet16 = new javax.swing.JButton();
        btnLet17 = new javax.swing.JButton();
        btnLet18 = new javax.swing.JButton();
        btnLet19 = new javax.swing.JButton();
        btnLet20 = new javax.swing.JButton();
        btnLet21 = new javax.swing.JButton();
        btnLet22 = new javax.swing.JButton();
        btnLet23 = new javax.swing.JButton();
        btnLet24 = new javax.swing.JButton();
        btnLet25 = new javax.swing.JButton();
        btnLet26 = new javax.swing.JButton();
        btnLet27 = new javax.swing.JButton();
        txtLineas = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Usuario: ");

        txtJugador.setEditable(false);
        txtJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtJugador.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Saldo: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Intentos:");

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtIntentos.setEditable(false);
        txtIntentos.setBackground(new java.awt.Color(255, 255, 255));
        txtIntentos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtIntentos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("ADIVINA EL POKEMON");

        panelImg.setBackground(new java.awt.Color(255, 255, 255));
        panelImg.setAlignmentX(0.0F);
        panelImg.setAlignmentY(0.0F);
        panelImg.setDoubleBuffered(false);
        panelImg.setEnabled(false);
        panelImg.setFocusable(false);
        panelImg.setMaximumSize(new java.awt.Dimension(504, 504));
        panelImg.setPreferredSize(new java.awt.Dimension(00, 00));

        img2.setAlignmentY(0.0F);
        img2.setIconTextGap(0);
        img2.setPreferredSize(new java.awt.Dimension(250, 250));

        img3.setAlignmentY(0.0F);
        img3.setIconTextGap(1);
        img3.setPreferredSize(new java.awt.Dimension(250, 250));

        img4.setBackground(new java.awt.Color(204, 204, 255));
        img4.setAlignmentY(0.0F);
        img4.setIconTextGap(1);
        img4.setPreferredSize(new java.awt.Dimension(250, 250));

        img1.setAlignmentY(0.0F);
        img1.setDoubleBuffered(true);
        img1.setFocusCycleRoot(true);
        img1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        img1.setIconTextGap(1);
        img1.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout panelImgLayout = new javax.swing.GroupLayout(panelImg);
        panelImg.setLayout(panelImgLayout);
        panelImgLayout.setHorizontalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgLayout.createSequentialGroup()
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImgLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelImgLayout.setVerticalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgLayout.createSequentialGroup()
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelBotones.setBackground(new java.awt.Color(0, 0, 255));

        btnLet1.setBackground(new java.awt.Color(0, 153, 255));
        btnLet1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet1.setForeground(new java.awt.Color(255, 255, 255));
        btnLet1.setText("A");
        btnLet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet1ActionPerformed(evt);
            }
        });

        btnLet2.setBackground(new java.awt.Color(0, 153, 255));
        btnLet2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet2.setForeground(new java.awt.Color(255, 255, 255));
        btnLet2.setText("B");
        btnLet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet2ActionPerformed(evt);
            }
        });

        btnLet3.setBackground(new java.awt.Color(0, 153, 255));
        btnLet3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet3.setForeground(new java.awt.Color(255, 255, 255));
        btnLet3.setText("C");
        btnLet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet3ActionPerformed(evt);
            }
        });

        btnLet4.setBackground(new java.awt.Color(0, 153, 255));
        btnLet4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet4.setForeground(new java.awt.Color(255, 255, 255));
        btnLet4.setText("D");
        btnLet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet4ActionPerformed(evt);
            }
        });

        btnLet5.setBackground(new java.awt.Color(0, 153, 255));
        btnLet5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet5.setForeground(new java.awt.Color(255, 255, 255));
        btnLet5.setText("E");
        btnLet5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet5ActionPerformed(evt);
            }
        });

        btnLet6.setBackground(new java.awt.Color(0, 153, 255));
        btnLet6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet6.setForeground(new java.awt.Color(255, 255, 255));
        btnLet6.setText("F");
        btnLet6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet6ActionPerformed(evt);
            }
        });

        btnLet7.setBackground(new java.awt.Color(0, 153, 255));
        btnLet7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet7.setForeground(new java.awt.Color(255, 255, 255));
        btnLet7.setText("G");
        btnLet7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet7ActionPerformed(evt);
            }
        });

        btnLet8.setBackground(new java.awt.Color(0, 153, 255));
        btnLet8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet8.setForeground(new java.awt.Color(255, 255, 255));
        btnLet8.setText("H");
        btnLet8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet8ActionPerformed(evt);
            }
        });

        btnLet9.setBackground(new java.awt.Color(0, 153, 255));
        btnLet9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet9.setForeground(new java.awt.Color(255, 255, 255));
        btnLet9.setText("I");
        btnLet9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet9ActionPerformed(evt);
            }
        });

        btnLet10.setBackground(new java.awt.Color(0, 153, 255));
        btnLet10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet10.setForeground(new java.awt.Color(255, 255, 255));
        btnLet10.setText("J");
        btnLet10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet10ActionPerformed(evt);
            }
        });

        btnLet11.setBackground(new java.awt.Color(0, 153, 255));
        btnLet11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet11.setForeground(new java.awt.Color(255, 255, 255));
        btnLet11.setText("K");
        btnLet11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet11ActionPerformed(evt);
            }
        });

        btnLet12.setBackground(new java.awt.Color(0, 153, 255));
        btnLet12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet12.setForeground(new java.awt.Color(255, 255, 255));
        btnLet12.setText("L");
        btnLet12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet12ActionPerformed(evt);
            }
        });

        btnLet13.setBackground(new java.awt.Color(0, 153, 255));
        btnLet13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet13.setForeground(new java.awt.Color(255, 255, 255));
        btnLet13.setText("M");
        btnLet13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet13ActionPerformed(evt);
            }
        });

        btnLet14.setBackground(new java.awt.Color(0, 153, 255));
        btnLet14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet14.setForeground(new java.awt.Color(255, 255, 255));
        btnLet14.setText("N");
        btnLet14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet14ActionPerformed(evt);
            }
        });

        btnLet15.setBackground(new java.awt.Color(0, 153, 255));
        btnLet15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet15.setForeground(new java.awt.Color(255, 255, 255));
        btnLet15.setText("Ñ");
        btnLet15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet15ActionPerformed(evt);
            }
        });

        btnLet16.setBackground(new java.awt.Color(0, 153, 255));
        btnLet16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet16.setForeground(new java.awt.Color(255, 255, 255));
        btnLet16.setText("O");
        btnLet16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet16ActionPerformed(evt);
            }
        });

        btnLet17.setBackground(new java.awt.Color(0, 153, 255));
        btnLet17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet17.setForeground(new java.awt.Color(255, 255, 255));
        btnLet17.setText("P");
        btnLet17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet17ActionPerformed(evt);
            }
        });

        btnLet18.setBackground(new java.awt.Color(0, 153, 255));
        btnLet18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet18.setForeground(new java.awt.Color(255, 255, 255));
        btnLet18.setText("Q");
        btnLet18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet18ActionPerformed(evt);
            }
        });

        btnLet19.setBackground(new java.awt.Color(0, 153, 255));
        btnLet19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet19.setForeground(new java.awt.Color(255, 255, 255));
        btnLet19.setText("R");
        btnLet19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet19ActionPerformed(evt);
            }
        });

        btnLet20.setBackground(new java.awt.Color(0, 153, 255));
        btnLet20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet20.setForeground(new java.awt.Color(255, 255, 255));
        btnLet20.setText("S");
        btnLet20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet20ActionPerformed(evt);
            }
        });

        btnLet21.setBackground(new java.awt.Color(0, 153, 255));
        btnLet21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLet21.setForeground(new java.awt.Color(255, 255, 255));
        btnLet21.setText("T");
        btnLet21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet21ActionPerformed(evt);
            }
        });

        btnLet22.setBackground(new java.awt.Color(0, 153, 255));
        btnLet22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet22.setForeground(new java.awt.Color(255, 255, 255));
        btnLet22.setText("U");
        btnLet22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet22ActionPerformed(evt);
            }
        });

        btnLet23.setBackground(new java.awt.Color(0, 153, 255));
        btnLet23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet23.setForeground(new java.awt.Color(255, 255, 255));
        btnLet23.setText("V");
        btnLet23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet23ActionPerformed(evt);
            }
        });

        btnLet24.setBackground(new java.awt.Color(0, 153, 255));
        btnLet24.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLet24.setForeground(new java.awt.Color(255, 255, 255));
        btnLet24.setText("W");
        btnLet24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet24ActionPerformed(evt);
            }
        });

        btnLet25.setBackground(new java.awt.Color(0, 153, 255));
        btnLet25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet25.setForeground(new java.awt.Color(255, 255, 255));
        btnLet25.setText("X");
        btnLet25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet25ActionPerformed(evt);
            }
        });

        btnLet26.setBackground(new java.awt.Color(0, 153, 255));
        btnLet26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet26.setForeground(new java.awt.Color(255, 255, 255));
        btnLet26.setText("Y");
        btnLet26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet26ActionPerformed(evt);
            }
        });

        btnLet27.setBackground(new java.awt.Color(0, 153, 255));
        btnLet27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLet27.setForeground(new java.awt.Color(255, 255, 255));
        btnLet27.setText("Z");
        btnLet27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLet27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(btnLet25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(btnLet19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(btnLet13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLet18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBotonesLayout.createSequentialGroup()
                                .addComponent(btnLet7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBotonesLayout.createSequentialGroup()
                                .addComponent(btnLet1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLet4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLet5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLet12, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(btnLet6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLet2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLet1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLet7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLet13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLet18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLet17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLet19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLet25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLet27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        txtLineas.setBackground(new java.awt.Color(0, 153, 102));
        txtLineas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtLineas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSalir.setBackground(new java.awt.Color(0, 153, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnSalir)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(txtLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Saldo:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet1ActionPerformed
        // TODO add your handling code here:
        verifica('A');
    }//GEN-LAST:event_btnLet1ActionPerformed

    private void btnLet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet2ActionPerformed
        // TODO add your handling code here:
        verifica('B');
    }//GEN-LAST:event_btnLet2ActionPerformed

    private void btnLet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet3ActionPerformed
        // TODO add your handling code here:
        verifica('C');
    }//GEN-LAST:event_btnLet3ActionPerformed

    private void btnLet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet4ActionPerformed
        // TODO add your handling code here:
        verifica('D');
    }//GEN-LAST:event_btnLet4ActionPerformed

    private void btnLet5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet5ActionPerformed
        // TODO add your handling code here:
        verifica('E');
    }//GEN-LAST:event_btnLet5ActionPerformed

    private void btnLet6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet6ActionPerformed
        // TODO add your handling code here:
        verifica('F');
    }//GEN-LAST:event_btnLet6ActionPerformed

    private void btnLet7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet7ActionPerformed
        // TODO add your handling code here:
        verifica('G');
    }//GEN-LAST:event_btnLet7ActionPerformed

    private void btnLet8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet8ActionPerformed
        // TODO add your handling code here:
        verifica('H');
    }//GEN-LAST:event_btnLet8ActionPerformed

    private void btnLet9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet9ActionPerformed
        // TODO add your handling code here:
        verifica('I');
    }//GEN-LAST:event_btnLet9ActionPerformed

    private void btnLet10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet10ActionPerformed
        // TODO add your handling code here:
        verifica('J');
    }//GEN-LAST:event_btnLet10ActionPerformed

    private void btnLet11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet11ActionPerformed
        // TODO add your handling code here:
        verifica('K');
    }//GEN-LAST:event_btnLet11ActionPerformed

    private void btnLet12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet12ActionPerformed
        // TODO add your handling code here:
        verifica('L');
    }//GEN-LAST:event_btnLet12ActionPerformed

    private void btnLet13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet13ActionPerformed
        // TODO add your handling code here:
        verifica('M');
    }//GEN-LAST:event_btnLet13ActionPerformed

    private void btnLet14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet14ActionPerformed
        // TODO add your handling code here:
        verifica('N');
    }//GEN-LAST:event_btnLet14ActionPerformed

    private void btnLet15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet15ActionPerformed
        // TODO add your handling code here:
        verifica('Ñ');
    }//GEN-LAST:event_btnLet15ActionPerformed

    private void btnLet16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet16ActionPerformed
        // TODO add your handling code here:
        verifica('O');
    }//GEN-LAST:event_btnLet16ActionPerformed

    private void btnLet17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet17ActionPerformed
        // TODO add your handling code here:
        verifica('P');
    }//GEN-LAST:event_btnLet17ActionPerformed

    private void btnLet18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet18ActionPerformed
        // TODO add your handling code here:
        verifica('Q');
    }//GEN-LAST:event_btnLet18ActionPerformed

    private void btnLet19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet19ActionPerformed
        // TODO add your handling code here:
        verifica('R');
    }//GEN-LAST:event_btnLet19ActionPerformed

    private void btnLet20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet20ActionPerformed
        // TODO add your handling code here:
        verifica('S');
    }//GEN-LAST:event_btnLet20ActionPerformed

    private void btnLet21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet21ActionPerformed
        // TODO add your handling code here:
        verifica('T');
    }//GEN-LAST:event_btnLet21ActionPerformed

    private void btnLet22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet22ActionPerformed
        // TODO add your handling code here:
        verifica('U');
    }//GEN-LAST:event_btnLet22ActionPerformed

    private void btnLet23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet23ActionPerformed
        // TODO add your handling code here:
        verifica('V');
    }//GEN-LAST:event_btnLet23ActionPerformed

    private void btnLet24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet24ActionPerformed
        // TODO add your handling code here:
        verifica('W');
    }//GEN-LAST:event_btnLet24ActionPerformed

    private void btnLet25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet25ActionPerformed
        // TODO add your handling code here:
        verifica('X');
    }//GEN-LAST:event_btnLet25ActionPerformed

    private void btnLet26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet26ActionPerformed
        // TODO add your handling code here:
        verifica('Y');
    }//GEN-LAST:event_btnLet26ActionPerformed

    private void btnLet27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLet27ActionPerformed
        // TODO add your handling code here:
        verifica('Z');
    }//GEN-LAST:event_btnLet27ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void seleccionaPalabra(){
        
       
        int n1=0;
        /*int n=personajes.size();
        int aux= (int)(Math.random() *n-1+0);
        personaje= personajes.get(aux);
        System.out.println(personajes.get(aux));*/
        n1=personaje.length();
        for(int i=0; i<n1-1; i++){
            palabraT+="_ ";
        }
        palabraT+="_";
       
        txtLineas.setText(palabraT);
        
        
    }
    
    private void llenarPalabras(){
        partida++;
        palabraT="";
        letrasUsadas="";
        contador=0;
        intentos=4;
        txtIntentos.setText(String.valueOf(intentos));
        int n1=0;
        int n=personajes.size();
        int aux;
        boolean bandera=true;
        do{
            bandera=true;
            aux= (int)(Math.random() *n-1+0);
            n1=personajes.get(aux).length();
           
            for (String partida : partidas) {
                if(personajes.get(aux).equals(partida)) bandera=false;
            }
            
        }while(bandera==false);
        
        personaje=personajes.get(aux);
        
        partidas.add(personaje);
                
    }
    
    
    public void cargar_imagen(String imagen){
        int j=1;
        String nombre="";
        for(int i=0; i<4; i++){
            nombre= imagen+j+".png";
            System.out.println(imagen);
            iconos[i] = new ImageIcon(getClass().getResource("/img/"+nombre));
            System.out.println(nombre);
            nombre="";
            j++;
           
        }
        
        switch(intentos){
            case 1: img1.setIcon(iconos[0]); 
            case 2: img2.setIcon(iconos[1]);
            case 3: img3.setIcon(iconos[2]);
            case 4: img4.setIcon(iconos[3]);
        }
        
    }
     
    public void verifica(char letra){
        boolean bandera = true;
        if(!"".equals(letrasUsadas)){
            for(int i=0; i<letrasUsadas.length(); i++){
                if(letrasUsadas.charAt(i) == letra){
                    bandera=false;
                }
            }
        }
        if(bandera== true){
            
            llenado(letra);
        }
    }
    
    private void llenado(char letra){ 
        String cadenaInicio="";
        String cadenaFinal="";
        boolean bandera=false;
        int j=0;
        int min=0; 
        int max=0;
        for(int i=0; i<personaje.length(); i++){
            //bandera=false;
            if(personaje.charAt(i) == letra){
                
                contador++;
              
                j=i*2;
                min=j-1;
                max=j+1;
               
                if(j==0){
                    cadenaFinal=palabraT.substring(1);
                    palabraT= letra+cadenaFinal;
                }else{
                    if(j==palabraT.length()-1){
                        cadenaInicio= palabraT.substring(0,palabraT.length()-1);
                        palabraT= cadenaInicio+letra;
                    }else{
                        cadenaInicio=palabraT.substring(0, j);
                        cadenaFinal=palabraT.substring(max,palabraT.length());
                        palabraT= cadenaInicio+letra+cadenaFinal;
                    }
                }
                letrasUsadas+=letra;
                bandera=true;
            }
        }
        
        if(bandera==false){
            cargar_imagen(personaje);
            intentos--;
            JOptionPane.showMessageDialog(null, "La letra "+ letra + " no se encuentra\n\nPerdiste una vida");
            
        }
          
            txtIntentos.setText(String.valueOf(intentos));
            txtLineas.setText("");
            txtLineas.setText(palabraT);
        
        if(intentos==0){
            jugador.setSaldo(jugador.getSaldo()-100);
            saldo-=100;
            JOptionPane.showMessageDialog(null, "Perdiste el pokemon era " + personaje);
            if(partida<3){
                llenarPalabras();
                img1.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                img2.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                img3.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                img4.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                seleccionaPalabra();
            }else{
                this.setVisible(false);
                new ResultadosJuego(jugador.getUser_name(), jugador.getSaldo(), saldo, ganadas).setVisible(true);
            }
           
            
        }
        if(contador== personaje.length()){
            jugador.setSaldo(jugador.getSaldo()+150);
            saldo+=150;
            ganadas++;
            JOptionPane.showMessageDialog(null, "Felicidades adivinaste el pokemon "+ personaje);
            if(partida<3){
                llenarPalabras();
                img1.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                img2.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                img3.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                img4.setIcon(new ImageIcon(getClass().getResource("/img/limpiar.png")));
                seleccionaPalabra();
            }else{
                this.setVisible(false);
                new ResultadosJuego(jugador.getUser_name(), jugador.getSaldo(), saldo, ganadas).setVisible(true);
            }
            
        }
       
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLet1;
    private javax.swing.JButton btnLet10;
    private javax.swing.JButton btnLet11;
    private javax.swing.JButton btnLet12;
    private javax.swing.JButton btnLet13;
    private javax.swing.JButton btnLet14;
    private javax.swing.JButton btnLet15;
    private javax.swing.JButton btnLet16;
    private javax.swing.JButton btnLet17;
    private javax.swing.JButton btnLet18;
    private javax.swing.JButton btnLet19;
    private javax.swing.JButton btnLet2;
    private javax.swing.JButton btnLet20;
    private javax.swing.JButton btnLet21;
    private javax.swing.JButton btnLet22;
    private javax.swing.JButton btnLet23;
    private javax.swing.JButton btnLet24;
    private javax.swing.JButton btnLet25;
    private javax.swing.JButton btnLet26;
    private javax.swing.JButton btnLet27;
    private javax.swing.JButton btnLet3;
    private javax.swing.JButton btnLet4;
    private javax.swing.JButton btnLet5;
    private javax.swing.JButton btnLet6;
    private javax.swing.JButton btnLet7;
    private javax.swing.JButton btnLet8;
    private javax.swing.JButton btnLet9;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelImg;
    private javax.swing.JTextField txtIntentos;
    private javax.swing.JTextField txtJugador;
    private javax.swing.JLabel txtLineas;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables

    private void setText(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
